# Generated by Django 5.2 on 2026-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('wymagana_sila_kg', models.IntegerField(default=0, verbose_name='Wymagana siła (kg)')),
                ('praca_stojaca', models.BooleanField(default=False, verbose_name='Praca stojąca')),
                ('praca_przy_monitorze', models.BooleanField(default=False, verbose_name='Praca przy monitorze')),
                ('wymaga_komputera', models.BooleanField(default=False, verbose_name='Wymaga komputera')),
                ('max_pracownikow', models.IntegerField(default=1, verbose_name='Maks. pracowników')),
                ('aktywne', models.BooleanField(default=True, verbose_name='Aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
                'ordering': ['nazwa'],
            },
        ),
    ]
