# Generated by Django 5.2.12 on 2026-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanowiska', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanowisko',
            name='powtarzalnosc_czynnosci',
            field=models.IntegerField(choices=[(1, 'Bardzo niski'), (2, 'Niski'), (3, 'Średni'), (4, 'Wysoki'), (5, 'Bardzo wysoki')], default=3, verbose_name='Powtarzalność czynności'),
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='poziom_chodzenia',
            field=models.IntegerField(choices=[(1, 'Bardzo niski'), (2, 'Niski'), (3, 'Średni'), (4, 'Wysoki'), (5, 'Bardzo wysoki')], default=3, verbose_name='Poziom chodzenia'),
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='poziom_siedzenia',
            field=models.IntegerField(choices=[(1, 'Bardzo niski'), (2, 'Niski'), (3, 'Średni'), (4, 'Wysoki'), (5, 'Bardzo wysoki')], default=3, verbose_name='Poziom siedzenia'),
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='praca_na_zewnatrz',
            field=models.BooleanField(default=False, verbose_name='Praca na zewnątrz'),
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='zakres_dzwigania',
            field=models.CharField(choices=[('0-5', '0–5 kg'), ('6-10', '6–10 kg'), ('11-15', '11–15 kg'), ('16-20', '16–20 kg'), ('>20', 'Powyżej 20 kg')], default='0-5', max_length=10, verbose_name='Zakres dźwigania'),
        ),
    ]
