# Generated by Django 5.2.12 on 2026-05-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanZmiany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pliku', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('zmiana', models.CharField(choices=[('dzienny', 'Plan dzienny (zmiana 1 i 2)'), ('nocny', 'Plan nocny (zmiana 3)')], max_length=10, verbose_name='Zmiana')),
                ('data_importu', models.DateTimeField(auto_now_add=True, verbose_name='Data importu')),
                ('dane_raw', models.JSONField(default=list, verbose_name='Dane surowe')),
                ('importowany_przez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importowany przez')),
            ],
            options={
                'verbose_name': 'Plan zmiany',
                'verbose_name_plural': 'Plany zmian',
                'ordering': ['-data_importu'],
            },
        ),
    ]
