# Generated by Django 5.2.12 on 2026-05-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0002_planzmiany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='stanowiska',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='zrodlo',
        ),
    ]
