# Generated by Django 5.2.12 on 2026-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0003_remove_pracownik_stanowiska_remove_pracownik_zrodlo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='doswiadczenie',
            field=models.JSONField(default=list, verbose_name='Doświadczenie'),
        ),
    ]
