# Generated by Django 5.2.12 on 2026-05-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0004_pracownik_doswiadczenie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pracownik',
            name='pracownik_unikalny_imie_nazwisko',
        ),
    ]
