# Generated by Django 5.2.12 on 2026-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0005_remove_pracownik_pracownik_unikalny_imie_nazwisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='planzmiany',
            name='dopasowane_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data dopasowania'),
        ),
        migrations.AddField(
            model_name='planzmiany',
            name='dopasowanie',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dopasowanie'),
        ),
        migrations.AlterField(
            model_name='planzmiany',
            name='dane_raw',
            field=models.JSONField(default=list, verbose_name='Wymagania obsady'),
        ),
    ]
