# Generated by Django 5.2.12 on 2026-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0006_planzmiany_dopasowane_at_planzmiany_dopasowanie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planzmiany',
            name='zmiana',
            field=models.CharField(choices=[('poranny', 'Plan poranny (zmiana 1)'), ('popobudniowy', 'Plan popołudniowy (zmiana 2)'), ('nocny', 'Plan nocny (zmiana 3)')], max_length=15, verbose_name='Zmiana'),
        ),
    ]
