# Generated by Django 5.2.12 on 2026-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0009_przydzial_dzienny'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandzienny',
            name='data_planu',
            field=models.DateField(blank=True, null=True, verbose_name='Data planu'),
        ),
    ]
