# Generated by Django 5.2 on 2026-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0012_pracownik_arkusz'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfiguracjazmian',
            name='zmiana_4',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='D', max_length=1, verbose_name='Zmiana D (PRASA/KDR)'),
        ),
        migrations.AlterField(
            model_name='konfiguracjazmian',
            name='zmiana_1',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Zmiana I'),
        ),
        migrations.AlterField(
            model_name='konfiguracjazmian',
            name='zmiana_2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=1, verbose_name='Zmiana II'),
        ),
        migrations.AlterField(
            model_name='konfiguracjazmian',
            name='zmiana_3',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=1, verbose_name='Zmiana III'),
        ),
    ]
