# Generated by Django 5.2 on 2026-05-22 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rekruci', '0001_initial'),
        ('stanowiska', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akcja', models.CharField(max_length=200, verbose_name='Akcja')),
                ('orzeczenie_dostepne', models.BooleanField(default=False, verbose_name='Orzeczenie dostępne')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='Adres IP')),
                ('rekrut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekruci.rekrut', verbose_name='Rekrut')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log audytu',
                'verbose_name_plural': 'Logi audytu',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Przydzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przydzialu', models.DateTimeField(auto_now_add=True, verbose_name='Data przydziału')),
                ('zrodlo', models.CharField(choices=[('ai', 'AI'), ('reczny', 'Ręcznie')], default='reczny', max_length=10, verbose_name='Źródło')),
                ('uzasadnienie', models.TextField(blank=True, verbose_name='Uzasadnienie')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('score_w_momencie_przydzialu', models.IntegerField(blank=True, null=True, verbose_name='Score w momencie przydziału')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='przydzialy_wydane', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('rekrut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekruci.rekrut', verbose_name='Rekrut')),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stanowiska.stanowisko', verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name': 'Przydział',
                'verbose_name_plural': 'Przydziały',
                'ordering': ['-data_przydzialu'],
            },
        ),
    ]
