# Generated by Django 5.2 on 2026-05-22 07:36

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekrut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('data_urodzenia', models.DateField(verbose_name='Data urodzenia')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekruci_dodani', to=settings.AUTH_USER_MODEL, verbose_name='Dodany przez')),
            ],
            options={
                'verbose_name': 'Rekrut',
                'verbose_name_plural': 'Rekruci',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='OrzeczenieLekarski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Status zdrowotny')),
                ('max_dzwiganie_kg', models.IntegerField(blank=True, help_text='Puste = brak ograniczeń', null=True, verbose_name='Maks. dźwiganie (kg)')),
                ('zakaz_stania', models.BooleanField(default=False, verbose_name='Zakaz pracy stojącej')),
                ('zakaz_pochylania', models.BooleanField(default=False, verbose_name='Zakaz pochylania')),
                ('zakaz_monitora_h', models.IntegerField(blank=True, help_text='Puste = brak ograniczeń', null=True, verbose_name='Maks. godz. przy monitorze')),
                ('inne_ograniczenia', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Inne ograniczenia')),
                ('data_badania', models.DateField(verbose_name='Data badania')),
                ('data_waznosci', models.DateField(verbose_name='Data ważności')),
                ('lekarz', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Lekarz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('rekrut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orzeczenie', to='rekruci.rekrut', verbose_name='Rekrut')),
            ],
            options={
                'verbose_name': 'Orzeczenie lekarskie',
                'verbose_name_plural': 'Orzeczenia lekarskie',
            },
        ),
        migrations.CreateModel(
            name='AnkietaFizyczna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_dzwiganie_kg', models.IntegerField(choices=[(0, '0 kg – brak'), (10, '10 kg'), (15, '15 kg'), (25, '25 kg'), (30, '30 kg')], default=0, verbose_name='Maks. dźwiganie (kg)')),
                ('komfort_stania', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Komfort stania (1-5)')),
                ('umiejetnosci_komputerowe', models.IntegerField(choices=[(0, 'Brak'), (1, 'Podstawy'), (2, 'Swobodnie'), (3, 'Zaawansowany')], default=0, verbose_name='Umiejętności komputerowe')),
                ('tempo_pracy', models.CharField(choices=[('wolne', 'Wolne'), ('zrownowazone', 'Zrównoważone'), ('szybkie', 'Szybkie')], default='zrownowazone', max_length=20, verbose_name='Tempo pracy')),
                ('preferuje_ruch', models.BooleanField(default=False, verbose_name='Preferuje ruch')),
                ('preferuje_stale_miejsce', models.BooleanField(default=False, verbose_name='Preferuje stałe miejsce')),
                ('preferuje_zespol', models.BooleanField(default=False, verbose_name='Preferuje pracę w zespole')),
                ('preferuje_samodzielnie', models.BooleanField(default=False, verbose_name='Preferuje pracę samodzielną')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('rekrut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ankieta', to='rekruci.rekrut', verbose_name='Rekrut')),
            ],
            options={
                'verbose_name': 'Ankieta fizyczna',
                'verbose_name_plural': 'Ankiety fizyczne',
            },
        ),
    ]
